/// Flutter icons BalloonNew
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BalloonNew
///      fonts:
///       - asset: fonts/BalloonNew.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class BalloonNew {
  BalloonNew._();

  static const _kFontFam = 'BalloonNew';

  static const IconData balloonicon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ac_unit = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData access_alarm = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData access_alarms = const IconData(0xe803, fontFamily: _kFontFam);
}
