/// Flutter icons MealIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MealIcons
///      fonts:
///       - asset: fonts/MealIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MealIcons {
  MealIcons._();

  static const _kFontFam = 'MealIcons';

  static const IconData aggga = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData accessible =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData account_balance =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData account_circle =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData drive_eta =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData restaurant =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData account_balance_wallet =
      const IconData(0xf008, fontFamily: _kFontFam);
}
